apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: static-deployment
  namespace: static
spec:
  selector:
    matchLabels:
      app: static-deployment
  replicas: 1 
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - name: 
        ports:
        - containerPort: 80
